name: Build and Test


on:
  push:
    branches: 
      - '**'        # matches every branch

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
 release:
   runs-on: ubuntu-latest
   env:
    PACKAGE_NAME: "Test" 
    
   steps:
   - uses: actions/checkout@v2
     with:
       fetch-depth: 0

   - name: Setup .NET
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 6.0.x

   - name: Install GitVersion
     uses: gittools/actions/gitversion/setup@v0.9.9
     with:
       versionSpec: '5.x'
       
   - name: Restore dependencies
     run: dotnet restore
     
   - name: Determine version
     id: gitversion             
     uses: gittools/actions/gitversion/execute@v0.9.9
     with: 
       useConfigFile: true
