name: release
on:

  push:
    branches: "**"
  workflow_dispatch:
  
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Installing SDK .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
         versionSpec: '5.x'
       
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with: 
         useConfigFile: true
         
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release -p:Version=${{  steps.gitversion.outputs.SemVer }}

      - name: Tagging
        uses: rickstaa/action-create-tag@v1
        with:
         tag: v${{ steps.gitversion.outputs.SemVer }}
         message: "v${{ steps.gitversion.outputs.SemVer }}"

