name: Build and Test


on:
  push:
    # runs on all branches
    branches: "**"

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
 build-and-test:
   runs-on: ubuntu-latest
    
   steps:
   - uses: actions/checkout@v2
     with:
       fetch-depth: 0

   - name: Setup .NET
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 6.0.x

   - name: Install GitVersion
     uses: gittools/actions/gitversion/setup@v0.9.9
     with:
       versionSpec: '5.x'
       
   - name: Restore dependencies
     run: dotnet restore
     
   - name: Determine version
     id: gitversion             
     uses: gittools/actions/gitversion/execute@v0.9.9
     with: 
       useConfigFile: true
      
   - name: Build
     run: dotnet build --no-restore -c Release -p:Version=${{ steps.gitversion.outputs.SemVer }}

   - name: Test
     run: dotnet test --no-build -c Release --verbosity normal

   #- name: Set version
   #  run: echo ${{steps.gitversion.outputs.SemVer}} > build-version.txt
   outputs:
    build_version: ${{ steps.gitversion.outputs.SemVer }}
    
 release:
   runs-on: ubuntu-latest
   needs: [build-and-test]
   if: always() && (contains(github.ref, '/heads/master') || contains(github.ref, '/tags/v'))
   env:
    PACKAGE_NAME: "Test" 
   
   steps:   
   - name: Upload artifcat
     uses: actions/upload-artifact@v2
     with:
         name: "Release_${{env.PACKAGE_NAME}}_${{ needs.build-and-test.outputs.build_version }}"
         path: build-version.txt  
   outputs:
    build_version: ${{ steps.gitversion.outputs.SemVer }}
    package_name: ${{env.PACKAGE_NAME}}
    
 deploy:
  needs: [release]
  uses: ./.github/workflows/deploy.yml
  with:
    package_name:  ${{ needs.release.outputs.package_name }}
    build_version: ${{ needs.release.outputs.build_version }}