name: deploy

on:
  workflow_call:
    inputs:
      release_identification:
        required: true
        type: string
      packages_octopus:
        required: true
        type: string
      packages_github:
        required: false
        type: string
      packages_tswbin:
        required: false
        type: string
    secrets:
       OCTOPUS_API_KEY:
        required: true    
       OCTOPUS_SERVER:
        required: true
       GITHUB_TOKEN:
        required: false          
jobs:
  deploy:
    runs-on: self-hosted
    if: always()   
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: "${{ inputs.release_identification }}"

      - name: Publish packages to GITHUB
        if: "${{ inputs.packages_github != '' }}"
        run: |
            IFS="," read -a packagesGithub <<< ${{ inputs.packages_github }}
            for i in "${packagesGithub[@]}"; do
              echo "Value: ${i}"
              dotnet nuget push "${i}" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" 
            done
