name: deploy-to-octopus

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: self-hosted
    
    steps:
      - name: Set version environment variable
        run: echo ${{ inputs.username }}
