name: deploy

on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: always()   
    steps:
      - name: Set version environment variable
        run: |
           echo "VERSION=${{ inputs.build_version }}" >> $GITHUB_ENV
           echo ${{ inputs.build_version }}
      