name: deploy

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: always()   
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Release

      - name: Set version environment variable
        run: echo ${{ inputs.package_name}}
      
      