name: release

on:
  push:
  #  branches: 
  #    - 'master'
  #  tags:
  #    - 'v*'

jobs:
 release:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
     with:
       fetch-depth: 0

   - name: Setup .NET
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 6.0.x

   - name: Restore dependencies
     run: dotnet restore

   - name: Install GitVersion
     uses: gittools/actions/gitversion/setup@v0.9.9
     with:
       versionSpec: '5.x'
       
   - name: Determine version
     id: gitversion
     uses: gittools/actions/gitversion/execute@v0.9.9
     with: 
       useConfigFile: true

   - name: Set build version 
     run: echo "BUILD_VERSION=${{steps.gitversion.outputs.SemVer}}" >> $GITHUB_ENV

   - name: Build
     run: dotnet build --no-restore -c Release -p:Version=${{ env.BUILD_VERSION }}

   - name: Test
     run: dotnet test --no-build -c Release --verbosity normal

 deploy:
     uses: anamariamendes/gpg-key-test/.github/workflows/deploy-to-octopus.yml@master
     with:
       username: mona
     secrets:
       token: ${{ env.BUILD_VERSION }}
