name: release

on:
  push:
  #  branches: 
  #    - 'master'
  #  tags:
  #    - 'v*'


jobs:
 release:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
     with:
       fetch-depth: 0

   - name: Setup .NET
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 6.0.x

   - name: Restore dependencies
     run: dotnet restore

   - name: Install GitVersion
     uses: gittools/actions/gitversion/setup@v0.9.9
     with:
       versionSpec: '5.x'
       
   - name: Determine version
     id: gitversion
     uses: gittools/actions/gitversion/execute@v0.9.9
     with: 
       useConfigFile: true

   - name: Set build version 
     id: base_config_data
     run: echo "BUILD_VERSION=${{steps.gitversion.outputs.SemVer}}" >> $GITHUB_ENV
     outputs:
      build_version: ${{ env.BUILD_VERSION }}
      package_name: "TestPackageName"
      
   - name: Build
     run: dotnet build --no-restore -c Release -p:Version=${{ env.BUILD_VERSION }}

   - name: Test
     run: dotnet test --no-build -c Release --verbosity normal

   - name: Set version
     run: echo ${{ env.BUILD_VERSION }} > build-version.txt
     
   - name: Upload artifcat
     uses: actions/upload-artifact@v2
     with:
         name: Release
         path: build-version.txt  
     
 deploy:
  needs: [release]
  uses: ./.github/workflows/deploy.yml
  with:
    package_name:  ${{ needs.release.outputs.package_name }}
    build_version: ${{ needs.release.outputs.build_version }}
