name: release
on:

  push:
    branches: "**"
   # tags: "!*"
  workflow_dispatch:
  
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest     
    env:
     PACKAGE_NAME: "Teste"
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Installing SDK .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
         versionSpec: '5.x'
       
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with: 
         useConfigFile: true
         
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release -p:Version=${{  steps.gitversion.outputs.SemVer }}
        
      - name: Publish Api
        run: dotnet publish  -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish/ -r linux-x64
      
      - name: Zip artifacts
        uses: vimtor/action-zip@v1
        with:
         dest: ${{env.PACKAGE_NAME}}.${{ steps.gitversion.outputs.SemVer }}.zip
         files: publish/
      
      - name: Upload artifcat
        uses: actions/upload-artifact@v2
        with:
         name: "Release_${{env.PACKAGE_NAME}}_${{ steps.gitversion.outputs.SemVer }}"
         path: ${{env.PACKAGE_NAME}}.${{ steps.gitversion.outputs.SemVer }}.zip    
            
      - name: Tagging
        uses: rickstaa/action-create-tag@v1
        with:
         tag: v${{ steps.gitversion.outputs.SemVer }}
         message: "v${{ steps.gitversion.outputs.SemVer }}"
  deploy:
   needs: [build]
   uses: ./.github/workflows/deploy.yaml@master
   with:
    release_identification:  "teste"
    packages_octopus: "dsfddd"
    packages_github: "oi.nupkg,oi2.nupkg"
   secrets:
    OCTOPUS_API_KEY: "dvfddfddf"
    OCTOPUS_SERVER: "dsfddf"