name: release
on:
  push:
    branches: "master"
    tags: "!*"
    pull_request:
     types:
      - labeled
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest     
    env:
     PACKAGE_NAME: "Teste"
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Installing SDK .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
         versionSpec: '5.x'
         
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with: 
         useConfigFile: true
         
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release -p:Version=${{  steps.bumpr.outputs.next_version  }}
        
      - name: Publish Api
        run: dotnet publish  -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish/ -r linux-x64
      
      - name: Zip artifacts
        uses: vimtor/action-zip@v1
        with:
         dest: ${{env.PACKAGE_NAME}}.${{ steps.bumpr.outputs.next_version  }}.zip
         files: publish/
      
      - name: Upload artifcat
        uses: actions/upload-artifact@v2
        with:
         name: "Release_${{env.PACKAGE_NAME}}_${{ steps.bumpr.outputs.next_version  }}"
         path: ${{env.PACKAGE_NAME}}.${{ steps.bumpr.outputs.next_version  }}.zip    
            
    # - name: Tagging
    #   uses: rickstaa/action-create-tag@v1
    #   with:
    #    tag: v${{ steps.bumpr.outputs.next_version  }}
    #    message: "v${{ steps.bumpr.outputs.next_version  }}"
      - name: Tagging
        run: |
          git tag v${{ steps.bumpr.outputs.next_version  }}
          git push origin v${{ steps.bumpr.outputs.next_version  }}
          
#  deploy:
#   needs: [build]
#   uses: anamariamendes/gpg-key-test/.github/workflows/deploy.yml@master
#   with:
#    release_identification:  "teste"
#    packages_octopus: "dsfddd"
#   secrets:
#    OCTOPUS_API_KEY: "dvfddfddf"
#    OCTOPUS_SERVER: "dsfddf"