name: release

on:
  push:
  #  branches: 
  #    - 'master'
  #  tags:
  #    - 'v*'

jobs:
 build:
   name: Build and Test
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Installing SDK .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 5.0.x
     - name: Restore
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore -c Release
     - name: Tests
       run: dotnet test --no-bu
# release:
#   runs-on: ubuntu-latest
#
#   steps:
#   - uses: actions/checkout@v2
#     with:
#       fetch-depth: 0
#
#   - name: Setup .NET
#     uses: actions/setup-dotnet@v1
#     with:
#       dotnet-version: 6.0.x
#
#   - name: Restore dependencies
#     run: dotnet restore
#
#   - name: Install GitVersion
#     uses: gittools/actions/gitversion/setup@v0.9.9
#     with:
#       versionSpec: '5.x'
#   - name: Determine version
#     id: gitversion
#     uses: gittools/actions/gitversion/execute@v0.9.9
#     with: 
#       useConfigFile: true
#
#   - name: Set build version (from gitversion)
#     if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
#     run: echo "BUILD_VERSION=${{steps.gitversion.outputs.SemVer}}" >> $GITHUB_ENV
#   - name: Set build version (from tag)
#     if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
#     run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
#
#   - name: Build
#     run: dotnet build --no-restore -c Release -p:Version=${{ env.BUILD_VERSION }}
#
#   - name: Test
#     run: dotnet test --no-build -c Release --verbosity normal
#
#   - name: Publish and package
#     run: |
#       dotnet pack ./src/Presentation.Sdk --no-build --no-restore -c Release -o packed/ -p:PackageVersion=${{ env.BUILD_VERSION }}
#       dotnet pack ./src/V1.Dtos --no-build --no-restore -c Release -o packed/ -p:PackageVersion=${{ env.BUILD_VERSION }}
#
#   - name: Create release on push to master
#     uses: softprops/action-gh-release@v1
#     if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
#     with:
#       files: packed/*.nupkg
#       tag_name: v${{ env.BUILD_VERSION }}
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#   - name: Create release on push tag
#     uses: softprops/action-gh-release@v1
#     if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
#     with:
#       files: packed/*.nupkg
#       prerelease: ${{ contains(github.ref, 'alpha') == true || contains(github.ref, 'beta') == true }}
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#   - name: Publish Packages
#     run: |
#       dotnet nuget add source --username vestas-power-solutions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vestas-power-solutions/index.json"
#       dotnet nuget push "packed/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
